name: OpenAeroStruct

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # OAS dependencies are specified in setup.py.
    - name: Install OAS and its dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install .

    # We need pySpline/pyGeo to run FFD tests.
    - name: Install pySpline and pyGeo
      run: |
        sudo apt-get install openmpi-bin libopenmpi-dev
        pip install mpi4py
        git clone https://github.com/mdolab/pyspline.git
        cd pyspline
        cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk
        make
        pip install -e .
        cd ..
        git clone https://github.com/mdolab/pygeo.git
        pip install -e ./pygeo
        export OMPI_MCA_btl=^openib

    - name: Install packages for tests and docs
      run: |
        pip install coverage coveralls testflo
    #    pip install travis-sphinx
    #    pip install --user travis-sphinx
    # - name: Lint with flake8
    #  run: |
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: |
        cd openaerostruct
        testflo -n 2 openaerostruct --coverage --coverpkg openaerostruct --cover-omit \*tests/\* --cover-omit \*docs/\*
    # - name: Build docs
    #  run: |
    #    cd openaerostruct/docs
    #    travis-sphinx build --source=.

    - name: Coverage check
      run: |
        coveralls --rcfile=../.coveragerc;
